wso2/mi-language-server

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/schema/generate/visitor/MediatorSchemaVisitor.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Constant.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
> Add improvement to handle target variable in connectors/modules

- pom.xml
$subject
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Add wso2 repos for release

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/ExpressionCompletionUtils.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/ExpressionCompletionsProvider.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/ExpressionHelperProvider.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/TryOutUtils.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/schema/generate/visitor/MediatorSchemaVisitor.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/tryout/CAPPCacheManager.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/tryout/TryOutHandler.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/tryout/debugger/DebugEventClient.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/tryout/pojo/MediatorTryoutRequest.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/factory/APIFactory.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/factory/ResourceFactory.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/api/APIResource.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Constant.java
- pom.xml
Fixes: https://github.com/wso2/mi-vscode/issues/982, https://github.com/wso2/mi-vscode/issues/827, https://github.com/wso2/mi-vscode/issues/653
> Improve tryout and expression completions

- .github/workflows/publish-release.yml
> Add Github workflow for Maven release

- org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/utils/platform/PlatformTest.java
> Remove unnecessary branch check in the Platform Tests

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/UISchemaMapper.java
- pom.xml
> Fix connector expression issue

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/connectors/entity/ConnectorAction.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediator/schema/generate/visitor/MediatorSchemaVisitor.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Constant.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
Resolves https://github.com/wso2/mi-vscode/issues/1058
> Support definitions in outputschema of connectors

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediatorService/AIConnectorHandler.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Constant.java
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiAgent.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiChat.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiRagChat.xsd
> Fix AI connector issues

- org.eclipse.lemminx/pom.xml
- pom.xml
> Update LS version

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/dependency/tree/visitor/MediatorDependencyVisitor.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediatorService/MediatorHandler.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediatorService/mediators/ThrottleMediator.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/factory/mediators/filter/ThrottleFactory.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/AccessType.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/AllowAccessType.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/ControlAccessType.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/DenyAccessType.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/Throttle.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/filter/throttle/ThrottlePolicies.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/serializer/mediator/qos/ThrottleMediatorSerializer.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Utils.java
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/mediators/430/templates/throttle.mustache
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/mediators/430/ui-schemas/throttle.json
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/mediators/440/templates/throttle.mustache
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/mediators/440/ui-schemas/throttle.json
Fixes: https://github.com/wso2/mi-vscode/issues/1062
> Fix throttle mediator xml generation

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediatorService/mediators/CacheMediator.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/resourceFinder/AbstractResourceFinder.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Utils.java
This PR will fix the below mentioned issues.
- https://github.com/wso2/mi-vscode/issues/1067
- https://github.com/wso2/mi-vscode/issues/1091
- https://github.com/wso2/mi-vscode/issues/1092
> Fix issues in the LS

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/SynapseLanguageService.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/ISynapseLanguageService.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/RestApiAdmin.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/SwaggerConstants.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/pojo/IsEqualSwaggersParam.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/SwaggerUtils.java
This provides support to compare two swagger files, whether there are any mismatch in the API structure. This validates paths, paramters and methods.
This to fix https://github.com/wso2/product-micro-integrator/issues/4095
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this …
> Add swagger comparison support

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiAgent.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiChat.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiRagChat.xsd
- pom.xml
> Update AI module xsd schemas

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/SynapseLanguageService.java
> $Subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Add fix for gRPC connector integrate

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiAddToKnowledge.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiAgent.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiChat.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiGetFromKnowledge.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/ai/aiRagChat.xsd
- pom.xml
Fix AI module XSD schemas to support expressions.
> Fix AI module XSD schemas

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/antlr4/org/eclipse/lemminx/util/synapse_expression/ExpressionLexer.g4
- org.eclipse.lemminx/src/main/antlr4/org/eclipse/lemminx/util/synapse_expression/ExpressionParser.g4
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/SynapseLanguageService.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/ISynapseLanguageService.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/CodeDiagnosticRequest.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/ExpressionValidator.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/SyntaxErrorListener.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/pojo/ExpressionError.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/expression/pojo/ExpressionValidationResponse.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Utils.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/XMLSyntaxErrorCode.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/diagnostics/LSPXMLParserConfiguration.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/synapse/validator/SynapseExpressionValidator.java
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/extensions/xerces/xmlmodel/msg/XMLMessages.properties
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/430/mediators/other/publishEvent.xsd
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/core/variable.xsd
- pom.xml
This PR adds validation support for synapse expression.
Related To: https://github.com/wso2/mi-vscode/issues/1102
> Add Synapse Expression Validation

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/resourceFinder/AbstractResourceFinder.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/resourceFinder/NewProjectResourceFinder.java
> Add filter to remove the unnecessary files from the unit test registry resource list

- .github/workflows/maven-release.yml
- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/connectors/AbstractConnectorLoader.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/mediatorService/AIConnectorHandler.java
- pom.xml
This PR,
1. Fixes some issues in the LS.
2. Configures the maven release plugin and the GitHub workflow flow.
> Fix LS issues & add maven release plugin

- .github/workflows/maven-release.yml
> Fix access issue for maven release

- org.eclipse.lemminx/pom.xml
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/Constant.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/utils/UISchemaMapper.java
- pom.xml
This PR will remove the generate sequence option when trying to edit an event integration.
> Improve Event Integration Form

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/syntaxTree/pojo/mediator/extension/ScriptLanguage.java
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/mediators/440/ui-schemas/script.json
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/schemas/440/mediators/extension/script.xsd
> Add graalJs to the script mediator language dropdown

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/parser/pom/PluginHandler.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/parser/pom/PomParser.java
- org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/inbound-endpoints/inbound_endpoints_440.json
This PR will fix the issue https://github.com/wso2/mi-vscode/issues/1229
> Resolve issues in the pom parser

- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/OpenAPIProcessor.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/RestApiAdmin.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/SwaggerConstants.java
- org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/api/generator/pojo/GenerateSwaggerParam.java
This PR will fix the issue https://github.com/wso2/mi-vscode/issues/1242
> Update OpenAPI spec generation flow

- org.eclipse.lemminx/pom.xml
> $Subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Update pom.xml with Connector Tool Version
